---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: apiserver-deployment
    labels:
        app: apiserver
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate 
    selector:
        matchLabels:
            app: apiserver
    template:
        metadata:
            labels:
                app: apiserver
        spec: 
            containers:
                - name: apiserver
                  image: zachhamilton/rt-retail-apiserver
                  env:
                    - name: CONFIG_TYPE
                      value: "ENV"
                  envFrom:
                    - secretRef:
                          name: kafka-secrets
                  ports:
                      - containerPort: 8080
                        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: apiserver-service
    labels: 
        app: apiserver
spec: 
    selector:
        app: apiserver
    ports:
        - name: apiserver-port
          port: 8080
          targetPort: 8080
          protocol: TCP
    type: LoadBalancer 
