---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: supplier-deployment
    labels:
        app: supplier
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate 
    selector:
        matchLabels:
            app: supplier
    template:
        metadata:
            labels:
                app: supplier
        spec: 
            containers:
                - name: supplier
                  image: zachhamilton/rt-retail-supplier
                  env: 
                    - name: CONFIG_TYPE
                      value: "ENV"
                  envFrom:
                    - secretRef:
                        name: kafka-secrets
---
