apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: commercial-se-cluster
  region: us-east-2
  
nodeGroups:
  - name: ng-public
    instanceType: m5.large
    desiredCapacity: 3
    subnets:
      - subnet-0c5ccaa6dab3ab852
      - subnet-04a86d75cbed2468c
      - subnet-02daef8bc23af900d